### ISSUE TITLE
Mime issue

### ISSUE THREAD

**Issue by ImKator** [omarsourour/ng-webchat-example#1]
Thank you for creating this!   Hard to find example of the chat bot.   When I try to serve this app, I get the following errors.   If you have any ideas, I would be grateful for any help.

![image](https://user-images.githubusercontent.com/32180064/52167532-8608e780-26d9-11e9-867c-0add04b1fc5a.png)

Just in case the image does not work.

ERROR in ./node_modules/mime/index.js
Module not found: Error: Can't resolve './types/other' in 'C:\Top\ng-webchat-example\node_modules\mime'
ERROR in ./node_modules/mime/index.js
Module not found: Error: Can't resolve './types/standard' in 'C:\Top\ng-webchat-example\node_modules\mime'

**Comment by ImKator** [comment]
ok, I managed to fix it locally, but I know this is not the right solution.   I added the .json extension to the files.  I will try to find the better way to resolve the files with Angular.  

module.exports = new Mime(require('./types/standard**.json**'), require('./types/other**.json**'));

**Comment by omarsourour** [comment]
Hello @ImKator .. You are 100%. I faced this issue when developing this sample, and opened a PR in the WebChat repo to address it. You will not have to be needing to this fix as of the next release of WebChat. For your reference, the PR is: Microsoft/BotFramework-WebChat#1686
