### ISSUE TITLE
Adaptive Card issue?

### ISSUE THREAD

**Issue by ImKator** [omarsourour/ng-webchat-example#2]
Omar, once again thanks for creating this.  I have this sample communicating with a test bot I have created, but I get the following markdown and adaptive card issues.   I think the markdown will be resolved in 4,3, but not sure if this code should support adaptive cards?   Please take a peek and see what you think.

![image](https://user-images.githubusercontent.com/32180064/53133216-899ccb00-352f-11e9-9351-f3f58e73a036.png)

**Comment by omarsourour** [comment]
Hello @ImKator .. I apologize for the delayed response. Can you please send me a snippet of the code/modifications that is causing you a problem?

**Comment by ImKator** [comment]
Thanks for responding Omar.  I am using whatever version your sample project sets.   I think this might be what you want.   
        "@angular/common": "^5.2.5",
        "@angular/compiler": "^5.2.5",
        "@angular/core": "^5.2.5",
        "@angular/http": "^5.2.5",
        "@angular/platform-browser": "^5.2.5",
        "@angular/platform-browser-dynamic": "^5.2.5",
        "@angular/router": "^5.2.5",


my code is very similar to yours, but when my service(bot) returns an adaptive care I get the error above.

**Comment by ImKator** [comment]
Hey Omar,  I'm going to close this.  I've not gotten it working, but I cannot get your code or another project using the latest angular(7.2).  Neither can connect to my bot.   If I use a plain html/CDN page the code can connect.  Using the latest from the CDN it works:
<script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>

Once again thanks for building this and if you get a botframework-webchat(v 4.3) working with angular, I will certainly check it out.

**Comment by ImKator** [comment]
This was a problem on my end, I am in fact able to connect the angular component to my bot. Thanks

**Comment by omarsourour** [comment]
@ImKator I am glad to hear that it was solved, because frankly I was drawing blanks as to why it wouldn't work :) .. Good luck.

**Comment by ImKator** [comment]
oh and I just got cards to work as well.  So this sample rocks!   I can send you what I have if you want, but essentially the same code works in angular 7+
